apiVersion: batch/v1
kind: Job
metadata:
  name: f3-evaluator
  annotations: { }
  labels: { }
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - env:
            - name: AICROWD_TESTS_FOLDER
              value: /tmp/debug-environments
          image:
          name: f3-evaluator
          pullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/debug-environments
              name: debug-environments
            - mountPath: /tmp/results
              name: fab-flatland3-results
      initContainers:
        - args:
            - -c
            - cd /tmp; unzip debug-environments.zip
          command:
            - /bin/sh
          image: busybox
          imagePullPolicy: IfNotPresent
          name: startup
          volumeMounts:
            - mountPath: /tmp/debug-environments.zip
              name: fab-flatland3-data-vol
              subPath: debug-environments.zip
            - mountPath: /tmp/debug-environments
              name: debug-environments
      volumes:
        - configMap:
            name: fab-flatland3-data
          name: fab-flatland3-data-vol
        - emptyDir: { }
          name: debug-environments
        - name: fab-flatland3-results
          persistentVolumeClaim:
            claimName:
