apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: [ 'sleep', 'infinity' ]
      volumeMounts:
        - name: mypvc
          mountPath: /data
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: fab-int-results
