apiVersion: batch/v1
kind: Job
metadata:
  labels: { }
  annotations: { }
  name: f3-submission
spec:
  template:
    spec:
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
      activeDeadlineSeconds: 7200
      restartPolicy: Never
      containers:
        - env:
            - name: AICROWD_TESTS_FOLDER
              value: /tmp
          image:
          pullPolicy: Always
          name: f3-submission
          volumeMounts:
            - mountPath: /tmp
              name: debug-environments
      initContainers:
        - args:
            - -c
            - cd /tmp; unzip debug-environments.zip
          command:
            - /bin/sh
          image: busybox
          imagePullPolicy: IfNotPresent
          name: startup
          volumeMounts:
            - mountPath: /tmp/debug-environments.zip
              name: fab-flatland3-data-vol
              subPath: debug-environments.zip
            - mountPath: /tmp/debug-environments
              name: debug-environments
      volumes:
        - configMap:
            name: fab-flatland3-data
          name: fab-flatland3-data-vol
        - emptyDir: { }
          name: debug-environments
