name: benchmarksubmitter
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - expat=2.6.3
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.12.7
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - amqp==5.3.1
      - billiard==4.2.1
      - celery==5.4.0
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - kombu==5.4.2
      - pip==24.2
      - prompt-toolkit==3.0.48
      - python-dateutil==2.9.0.post0
      - redis==5.2.1
      - setuptools==75.1.0
      - six==1.17.0
      - tzdata==2024.2
      - vine==5.1.0
      - wcwidth==0.2.13
      - wheel==0.44.0
