apiVersion: batch/v1
kind: Job
metadata:
  labels: { }
  annotations: { }
  name: f3-submission
spec:
  template:
    spec:
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
      activeDeadlineSeconds: 7200
      restartPolicy: Never
      containers:
        - env:
            - name: AICROWD_TESTS_FOLDER
              value: /tmp
          image:
          pullPolicy: Always
          name: f3-submission
          volumeMounts:
            - mountPath: /tmp
              name: environments
      initContainers:
        - command:
            - aws
            - s3
            - cp
            - s3://fab-data/flatland3/environments.zip
            - /tmp/environments
          env: [ ]
          image: amazon/aws-cli
          imagePullPolicy: IfNotPresent
          name: download-environments
          volumeMounts:
            - mountPath: /tmp/environments
              name: environments
        - args:
            - -c
            - |
              set -euxo pipefail
              find /tmp
              unzip /tmp/environments/environments.zip -d /tmp/environments/
              find /tmp
          command:
            - /bin/bash
          image: busybox
          imagePullPolicy: IfNotPresent
          name: extract-environments
          volumeMounts:
            - mountPath: /tmp/environments
              name: environments
      volumes:
        - emptyDir: { }
          name: environments

