# compose file for local dev

services:
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres
    # If persistent storage is required, uncomment volumes list:
    # volumes:
      # - ${POSTGRES_VOLUME:-./var/postgres}:/var/lib/postgresql/data:delegated

  flyway:
    extends:
      file: docker-compose-base.yml
      service: flyway


  pgadmin:
    extends:
      file: docker-compose-base.yml
      service: pgadmin

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis

  redis-monitor:
    extends:
      file: docker-compose-base.yml
      service: redis-monitor

  rabbit:
    extends:
      file: docker-compose-base.yml
      service: rabbit

  minio:
    extends:
      file: docker-compose-base.yml
      service: minio

  minio_setup:
    extends:
      file: docker-compose-base.yml
      service: minio_setup

  orchestrator:
    extends:
      file: docker-compose-base.yml
      service: orchestrator

  keycloak:
    extends:
      file: docker-compose-base.yml
      service: keycloak

networks:
  flatland-benchmarks:
