# compose file for testing

services:
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres

  flyway:
    extends:
      file: docker-compose-base.yml
      service: flyway
    # data is not present in docker-compose-base but required for test
    volumes:
      - ./migration/schema:/flyway/sql/schema
      - ./migration/data:/flyway/sql/data

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis

  redis-monitor:
    extends:
      file: docker-compose-base.yml
      service: redis-monitor

  rabbit:
    extends:
      file: docker-compose-base.yml
      service: rabbit

  minio:
    extends:
      file: docker-compose-base.yml
      service: minio

  minio_setup:
    extends:
      file: docker-compose-base.yml
      service: minio_setup

  compute_worker:
    extends:
      file: docker-compose-base.yml
      service: compute_worker

networks:
  flatland-benchmarks:
