services:
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis

  redis-monitor:
    extends:
      file: docker-compose-base.yml
      service: redis-monitor

  rabbit:
    extends:
      file: docker-compose-base.yml
      service: rabbit

  minio:
    extends:
      file: docker-compose-base.yml
      service: minio

  minio_setup:
    extends:
      file: docker-compose-base.yml
      service: minio_setup

  compute_worker:
    extends:
      file: docker-compose-base.yml
      service: compute_worker

  fab-backend:
    image: ghcr.io/flatland-association/fab-backend:latest
    pull_policy: always
    # POSTGRES_ variables are required for flyway
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST:-rabbit}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      rabbit:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./config-demo.jsonc:/usr/src/app/dist/backend/config/config.jsonc
      # for demo, mount data migration
      - ../ts/backend/src/migration/data:/flyway/sql/data
    ports:
      - 8000:8000
    networks:
      - flatland-benchmarks

  fab-frontend:
    image: ghcr.io/flatland-association/fab-frontend:latest
    pull_policy: always
    depends_on:
      rabbit:
        condition: service_healthy
    ports:
      - 80:80

networks:
  flatland-benchmarks:
