# compose file for testing

services:
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres

  flyway:
    extends:
      file: docker-compose-base.yml
      service: flyway

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis

  redis-monitor:
    extends:
      file: docker-compose-base.yml
      service: redis-monitor

  rabbit:
    extends:
      file: docker-compose-base.yml
      service: rabbit

  minio:
    extends:
      file: docker-compose-base.yml
      service: minio

  minio_setup:
    extends:
      file: docker-compose-base.yml
      service: minio_setup

  orchestrator:
    extends:
      file: docker-compose-base.yml
      service: orchestrator

networks:
  flatland-benchmarks:
