services:
  postgres:
    extends:
      file: docker-compose-base.yml
      service: postgres

  redis:
    extends:
      file: docker-compose-base.yml
      service: redis

  redis-monitor:
    extends:
      file: docker-compose-base.yml
      service: redis-monitor

  rabbit:
    extends:
      file: docker-compose-base.yml
      service: rabbit

  minio:
    extends:
      file: docker-compose-base.yml
      service: minio

  minio_setup:
    extends:
      file: docker-compose-base.yml
      service: minio_setup

  compute_worker:
    extends:
      file: docker-compose-base.yml
      service: compute_worker

  fab-backend:
    image: ghcr.io/flatland-association/fab-backend:latest
    pull_policy: always
    depends_on:
      rabbit:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./config.jsonc:/usr/src/app/dist/backend/config/config.jsonc
    ports:
      - 8000:8000
    networks:
      - flatland-benchmarks

  fab-frontend:
    image: ghcr.io/flatland-association/fab-frontend:latest
    pull_policy: always
    depends_on:
      rabbit:
        condition: service_healthy
    ports:
      - 80:80

networks:
  flatland-benchmarks:
