apiVersion: batch/v1
kind: Job
metadata:
  labels: { } # INSERTED
  annotations: { }
  name: f3-sub
spec:
  backoffLimit: 1
  template:
    spec:
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
      activeDeadlineSeconds: 7200
      restartPolicy: Never
      containers:
        - name: f3-submission
          image: INSERTED
          imagePullPolicy: Always
          imagePullSecrets:
            - name: default-secret
          args: [ ] # INSERTED
          volumeMounts:
            - name: pvc-submissions
              mountPath: /data
              subPath: # INSERTED /<submission_id> in the pvc mounted as /data/<submission_id>
            - name: environments
              mountPath: /tmp/environments

      initContainers:
        - name: download-environments
          command:
            - sh
          args:
            - -c
            - |
              set -euxo pipefail
              aws s3 cp  ${S3_URL_ENVIRONMENTS_ZIP} /tmp/environments
          env: [ ] # INSERTED
          image: amazon/aws-cli
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/environments
              name: environments
        - name: extract-environments
          args:
            - -c
            - |
              set -euxo pipefail
              find /tmp
              unzip /tmp/environments/environments.zip -d /tmp/environments/
              find /tmp
              ls -al /data
              # /<submission_id>/<test_id>/<scenario_id> in the pvc mounted under /data:
              mkdir -p ${DATA_DIR}
              ls -al /data
          command:
            - sh
          env: [ ] # INSERTED
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/environments
              name: environments
            - name: pvc-submissions
              mountPath: /data
      volumes:
        - emptyDir: { }
          name: environments
        - name: pvc-submissions
          persistentVolumeClaim:
            claimName: # INSERTED

