apiVersion: batch/v1
kind: Job
metadata:
  labels: { } # INSERTED
  annotations: { }
  name: f3-sub
spec:
  backoffLimit: 1
  template:
    spec:
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#handling-pod-and-container-failures
      # https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy
      activeDeadlineSeconds: 7200
      restartPolicy: Never
      containers:
        - name: f3-submission
          image: INSERTED
          imagePullPolicy: Always
          imagePullSecrets:
            - name: default-secret
          command: INSERTED
          volumeMounts:
            - name: pvc-fab-int-submissions
              mountPath: /data
              subPath:
            - name: environments
              mountPath: /tmp/environments

      initContainers:
        - name: download-environments
          command:
            - aws
            - s3
            - cp
            - s3://fab-data/flatland3/environments.zip
            - /tmp/environments
          env: [ ] # INSERTED
          image: amazon/aws-cli
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/environments
              name: environments
        - name: extract-environments
          args:
            - -c
            - |
              set -euxo pipefail
              find /tmp
              unzip /tmp/environments/environments.zip -d /tmp/environments/
              find /tmp
              mkdir -p /data/${PREFIX}
              find /data
          command:
            - sh
          env: [ ] # INSERTED
          image: busybox
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/environments
              name: environments
            - name: pvc-fab-int-submissions
              mountPath: /data
      volumes:
        - emptyDir: { }
          name: environments
        - name: pvc-fab-int-submissions
          persistentVolumeClaim:
            claimName: fab-int-submissions

