name: Checks

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-evaluation-compute-worker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run sandbox
        run: |
          docker compose build
          docker compose up

