name: Checks

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-evaluation-compute-worker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Download debug environments
        run: |
          wget "https://data.flatland.cloud/benchmarks/Flatland3/debug-environments.zip" -O debug-environments.zip
          unzip -o debug-environments.zip -d evaluation/evaluator
          find .
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r evaluation/requirements-dev.txt
          pip install -r evaluation/compute_worker/requirements.txt
      - name: Run tests
        working-directory: ./evaluation/
        run: pytest -s
