name: Build Keycloak Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true

env:
  NODE_VERSION: 16
  JAVA_VERSION: 21

defaults:
  run:
    shell: bash

jobs:
  build-image:
    name: Build Custom Keycloak Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deployment/frontend/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/flatland-association/fab:${{ github.event.inputs.tag }}
