name: Build FAB Flatland evaluator and submission template images and upload to ghcr.io

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true

env:
  NODE_VERSION: 16
  JAVA_VERSION: 21

defaults:
  run:
    shell: bash

jobs:
  build-flatland-evaluator:
    name: Build Flatland Evaluator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          context: evaluation/evaluator
          file: evaluation/evaluator/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/flatland-association/fab-flatland-evaluator:${{ github.event.inputs.tag }}
  build-flatland-submission-template:
    name: Build Flatland Submission Template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          context: evaluation/submission_template
          file: evaluation/submission_template/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/flatland-association/fab-flatland-submission-template:${{ github.event.inputs.tag }}
