name: Publish FAB Client Lib to Test PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Update version and build client lib
        working-directory: ./evaluation/ai4realnet_orchestrators/fab-clientlib
        run: |
          python -m pip install --upgrade build poetry
          poetry version ${{ inputs.version }}
          python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ./evaluation/ai4realnet_orchestrators/fab-clientlib
      - name: Archive package
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: ./evaluation/ai4realnet_orchestrators/fab-clientlib
